### ISSUE TITLE
Critique Globale

### ISSUE THREAD

**Issue by ShabSendra** [PirateTeamDDJV12/TeamWorkPirate#6]
Suite aux différentes pull request et après avoir eu assez de temps pour voir comment le projets évoluer, je me dois et je suis en mesure d'apporter quelques critiques constructives

Tout d'abords au niveau du code (principalement après avoir regarder ton code @SunlayGGX) :
- utiliser `using Namespace::Classname` au lieu de `using namespace Namespace` (dans les .cpp) pour garder le namespace le plus intacte possible.
- Utiliser des .hpp au lieu des .h. (".h" = C - ".hpp" = C++) (Question de clarté, certains analyseur statique se fie a l'extension pour se mettre dans un certain mode)
- Il faut décider entre at et la surchage d'op [], cela rajoute du code pour rien et le rend illisible.
- Constructeur de copy : array non alloué, et les attributs non seté correctement SEGFAULT (Corrigé par @obonnema )
- Il faut se décider sur les conventions : soit fonctions dans le .cpp soit dans le .hpp pas les deux ( Sauf cas de class/struct/fonction template)
- Appeler via this->foo() ou foo() pas les deux
- Soit `using std::ifstream`(etc...) dans les fonctions, soit pas, pas les deux (surtout quand on l'utilise qu'une fois)
- -Il faut arrêter d'utiliser C++11 ou supérieur juste pour faire beau ( Je fais référence par exemple au std::for_each avec une lambda horrible sachant que un simple for aurait été plus lisible mais qui plus est depuis C++ 11 le language dispose d'un for each)
- Les exceptions doivent héritées des bonnes exceptions de la STL (c-a-d http://en.cppreference.com/w/cpp/error/exception). Sinon cela peut amener a des exception jamais catché.
- Vect3f et Vertex sont sémantiquement une valeur(cf value semantic vs reference semantic), donc une struct avec des attributs publiques serait plus approprié.
- Faire attention à ce que représente les fonctions, `operator-=` devrait être défini grâce a `operator-` et pas le contraire ! trop de copies inutiles !
- Dans Vertex.cpp writeVecIntoStdString est à refaire (pas fonctionnel) + valueToWrite ne sert a rien !!

Maintenant au niveau de la conception du projet :

A trop vouloir séparer le travail cela donne une conception qui n'a ni queue ni tête, je m'explique, une Heightmap par définition est un tableau de points, le projet contient déja beaucoup trop de classes inutiles je pense particulièrement aux classes VertexArray et TriangleArray qui aurait pus être tout simplement remplacer par `std::vector<Vertex>`. Le projet est déjà tentaculaire alors qu'il consiste juste à lire un fichier de Heightmap et de construire un terrain avec.

Pour remédier à cela je propose la conception suivantes :

Une classe Heightmap qui s'occupe de lire le fichier fourni à la construction et stock les points (Vec3f) dans un std::vector<Vect3f>

Une classe Terrain qui possède un constructeur prenant en paramètre une `const &Heightmap` qui construit les vertices/vertexes à partir des data de la Heightmap. Cette classe s'occupe aussi de calculer les normales. Elle possède aussi une fonction Draw() non implémenté encore qui enverra les données au GPU pour déssiner le terrain.

Bien sur c'est ouvert à la discussion.

**Comment by SunlayGGX** [comment]
Merci pour ces critiques constructives. Je vais cependant répondre à chacun de ces points, 1 à 1 car j'ai l'impression que tu m'en veux un peu
pour les remarques que j'ai faite quand j'ai review le code d'Olivier. 
Cependant, dans un pull request, il s'agit de review du code et dire ce qui ne va pas. Je vous invite à faire de même avec moi et de ne pas le prendre mal s'il-vous-plait.
- utiliser using Namespace::Classname au lieu de using namespace Namespace (dans les .cpp) pour garder le namespace le plus intacte possible.

Oui, c'est vrai que j'aurais pu mais c'est chiant puisque j'utiliserais toujours mon namespace qui sera toujours le même. 
Je fais ce que tu préconise pour d'autre namespace mais pas les namespaces que je créer moi-même.
- Utiliser des .hpp au lieu des .h. (".h" = C - ".hpp" = C++) (Question de clarté, certains analyseur statique se fie a l'extension pour se mettre dans un certain mode)

Même Patrice utilise les .h et mon visual studio créer des .h. La différence entre .h et .hpp est nul ET cela serait vraiment chiant de renommer toutes les 
extensions de mes fichiers après création, d'enlever mes fichier et de les réinclure. Non, des .h c'est très bien...
- Il faut décider entre at et la surchage d'op [], cela rajoute du code pour rien et le rend illisible.

La classe std::vector a les 2 si je ne m'abuse. Le fait que je vous ai donné les 2 c'est justement pour que
ceux qui ont l'habitude d'utiliser soit l'1 soit l'autre ne change pas les habitude. Je rend mon code utilisable
pour d'autre le plus facilement possible. Bien entendu, je ne peux pas penser à tout mais une classe bien fournie, 
c'est super non?
- Constructeur de copy : array non alloué, et les attributs non seté correctement SEGFAULT (Corrigé par @obonnema )

Oui, c'est Olivier et moi qui l'avons corrigé. Je m'en excuse mais nous pouvons tous commettre des erreurs ou des oublis.
Je ne connais aucun codeur qui n'ai jamais fait d'oubli dans la vie et c'est le but des pull request d'éviter cela.
C'est pour cela que je vous invite à regarder attentivement chaque pull request et de commenter si quelque chose ne va pas.
- Il faut se décider sur les conventions : soit fonctions dans le .cpp soit dans le .hpp pas les deux ( Sauf cas de class/struct/fonction template)

-> Les templates peuvent se faire dans le cpp... De même que les classes et les structures
-> Si tu remarque bien, il y a déjà des convventions : 2 lignes maximums pour les fonctions (hors entête) dans le .h, sinon .cpp
-> Le inlining est rapide donc quand on le peux -> dans .h
-> Si tu remarque bien, j'ai mis dans le .cpp les méthodes compliqués même s'il n'y a moins de 2 lignes OU les méthodes qui appelle des classes
prototypées non implémentée dans le .h. Je fais l'include dans le .cpp (pour faire économiser du temps de compilation et éviter de recompiler plein pot)
- Appeler via this->foo() ou foo() pas les deux

Effectivement. Remarque justifiée. Mais j'utilise jamais this-> SAUF si je juge que sans celui-ci, c'est ambigu pour celui qui va relire mon code 
(dont moi dans 6 mois). Ce jugement d'ambiguité est tout à fait subjectif et non transposable d'un individu à l'autre.
- Soit using std::ifstream(etc...) dans les fonctions, soit pas, pas les deux (surtout quand on l'utilise qu'une fois)

Ok, my bad. Remarque justifiée.

-Il faut arrêter d'utiliser C++11 ou supérieur juste pour faire beau ( Je fais référence par exemple au std::for_each avec une lambda horrible sachant que un simple for aurait été plus lisible mais qui plus est depuis C++ 11 le language dispose d'un for each)

Je te rappelle le TP pour la séance S06 de Patrice... C'est ce que l'on nous impose. Et je ne fait pas le beau, j'utilise ce rush JUSTEMENT pour m'entrainer et essayer de nouvelles choses.
M'élever un peu en codage et non toujours rester au niveau bébé... Mais ça c'est un choix personnel qui ne regarde que moi.
- Les exceptions doivent héritées des bonnes exceptions de la STL (c-a-d http://en.cppreference.com/w/cpp/error/exception). Sinon cela peut amener a des exception jamais catché.

Dis ça à Patrice... Je ne fais qu'appliquer ce que l'on m'apprend. (on peut les catcher. De plus, c'est exceptions dont tu parle n'offre qu'une chose de plus, des explications
incompréhensibles (erreur de lecture de mémoire à l'emplacement 0xFFFFFEA32F...). Qu'est-ce que tu vas faire avec ça?...). Moi, je n'ai besoin que d'un crash d'appli. Les explications
personnes ne les lit et même si on les lisait, cela ne nous servirait à rien, on lance le debugger et on ferait du pas-à-pas pour corriger...
- Vect3f et Vertex sont sémantiquement une valeur(cf value semantic vs reference semantic), donc une struct avec des attributs publiques serait plus approprié.

Pour moi, jamais de variable publique. Une struct est pour moi une classe de stockage, pas de traitement mais cela n'est que subjectif et ne regarde que moi. Le code final est le même. On fait du C++, pas du C. Je prône l'encapsulation des variables. 
Même s'il y a getter et setter, ce n'est pas une raison de tout passer en public. Mais encore une fois, cela ne regarde que ma façon de coder.
- Faire attention à ce que représente les fonctions, operator-= devrait être défini grâce a operator- et pas le contraire ! trop de copies inutiles !

Ok, propose moi une version où on fait l'inverse. Plus optimisé que celle-ci et surtout que si on veux faire un changement, on ne change qu'1 seule fois à 1 endroit.
- Dans Vertex.cpp writeVecIntoStdString est à refaire (pas fonctionnel) + valueToWrite ne sert a rien !!

Constant viens de le corriger. Merci pour l'info. C'est comme cela que l'on s'améliore
Mais on peut tous commettre des erreurs, là encore, il faut relire le code dans les pull request et ne pas hésiter à le dire.

Maintenant au niveau de la conception du projet :
- A trop vouloir séparer le travail cela donne une conception qui n'a ni queue ni tête, je m'explique, une Heightmap par définition est un tableau de points, 

Remarque justifiée qui demande réflexion.
- le projet contient déja beaucoup trop de classes inutiles je pense particulièrement aux classes VertexArray et TriangleArray qui aurait pus être tout simplement remplacer par 
  std::vector<Vertex>. Le projet est déjà tentaculaire alors qu'il consiste juste à lire un fichier de Heightmap et de construire un terrain avec.

Là je ne suis pas d'accord. Plus il y a d'objet pour un programme, plus il y a de brique pour construire sa maison. il faut juste que son objet assure la cohérence de son objectif
et de ses invariants. De plus, je te rappelle que nous voulons :

****\* 1ère partie du tableau avec les Vertex

1 xPosition1 yPosition1 zPosition1 xNormale1 yNormale1 zNormale1
2 xPosition2 yPosition2 zPosition2 xNormale2 yNormale2 zNormale2
3 xPosition3 yPosition3 zPosition3 xNormale3 yNormale3 zNormale3
...
n xPositionN yPositionN zPositionN xNormaleN yNormaleN zNormaleN

***\* 2ème partie avec les triangles et TriangleArray

1 5 6
0 6 1
1 6 7
1 7 2
2 7 8
2 8 3
...

Et j'aimerais bien que tu me proposes une solution simple et réutilisable pour créer un tableau de triangle sans avoir défini ce qu'était un triangle.
En tout cas, c'est ma façon de coder et d'aborder les problèmes => quand on a un problème complexe, on le brise en ensemble de sous problèmes élémentaires et une classe résout 1 problème en particulier. C'est l'ensemble qui résout le problème de départ. Une classe qui résout 10 problèmes à la fois n'est pas une bonne idée, c'est d'expérience que je le dis...

Pour remédier à cela je propose la conception suivantes :
- Une classe Heightmap qui s'occupe de lire le fichier fourni à la construction et stock les points (Vec3f) dans un std::vector

Idée recevable. On en discutera.
- Une classe Terrain qui possède un constructeur prenant en paramètre une const &Heightmap qui construit les vertices/vertexes à partir des data de la Heightmap. Cette classe s'occupe aussi de calculer les normales. Elle possède aussi une fonction Draw() non implémenté encore qui enverra les données au GPU pour déssiner le terrain.

Idée qui pour moi est non recevable. Une classe fourre-tout en somme. Et pourquoi pas tout faire dans le main.cpp à ce moment là, c'est encore plus simple. 

Encore une fois : quand on a un problème complexe, on le brise en ensemble de sous problèmes élémentaires et une classe résout 1 problème en particulier. C'est l'ensemble qui résout le problème de départ. Une classe qui résout 10 problèmes à la fois n'est pas une bonne idée, c'est d'expérience que je le dis...

**Comment by ShabSendra** [comment]
Merci d'avoir répondu sous peu. Je n'ai absolument rien contre toi j'ai émis des critiques constructives et pour la plupart objectives mais je suis désolé de voir que la majorité de tes réponse se cachent derrière cette excuse.

Je vais reprendre quelques point pour démontrer tout 

> > utiliser using Namespace::Classname au lieu de using namespace Namespace (dans les .cpp) pour garder le namespace le plus intacte possible.
> 
> Oui, c'est vrai que j'aurais pu mais c'est chiant puisque j'utiliserais toujours mon namespace qui sera toujours le même. 
> Je fais ce que tu préconise pour d'autre namespace mais pas les namespaces que je créer moi-même.

Ce n'est pas vraiment une réponse, tu admets toi même tu es conscient que tu fais deux choses différentes qui devrait être les même sous prétexte que c'est chiant. Nous sommes une équipe il faut penser aux autres avant de penser à soi.

> > Utiliser des .hpp au lieu des .h. (".h" = C - ".hpp" = C++) (Question de clarté, certains analyseur statique se fie a l'extension pour se mettre dans un certain mode)
> 
> Même Patrice utilise les .h et mon visual studio créer des .h. La différence entre .h et .hpp est nul ET cela serait vraiment chiant de renommer toutes les 
> extensions de mes fichiers après création, d'enlever mes fichier et de les réinclure. Non, des .h c'est très bien...

Nous sommes des grands garçons nous pouvons éviter de faire les même chose que Patrice lorsque nous pensons que nos idées sont meilleurs. Le fait de dire que la différence entre un .h et un .hpp est nul cela peut aussi s'appliquer pour un .toz et .hpp, mais que fais tu de mes deux remarques concernant premièrement la cohérence des extensions (pour le c++ soit .hpp et .cpp soit .hxx et .cxx) qui est quasi universelle, les différents éditeurs de textes (tout le monde ne travaille pas avec visual studio) ainsi que les analyseurs statiques. J'aimerais donc savoir si la différence entre un .h et un .hpp est toujours nulle.

> > Il faut décider entre at et la surchage d'op [], cela rajoute du code pour rien et le rend illisible.
> 
> La classe std::vector a les 2 si je ne m'abuse. Le fait que je vous ai donné les 2 c'est justement pour que
> ceux qui ont l'habitude d'utiliser soit l'1 soit l'autre ne change pas les habitude. Je rend mon code utilisable
> pour d'autre le plus facilement possible. Bien entendu, je ne peux pas penser à tout mais une classe bien fournie, 
> c'est super non?

Cette remarque était juste par soucis de préservation de cohérence entre nos différents code, si quelqu'un dans l'équipe est prêt à utiliser ton `at` au lieu de l'opérateur `[]` alors pourquoi pas le laisser.

> > Constructeur de copy : array non alloué, et les attributs non seté correctement SEGFAULT (Corrigé par @obonnema )
> 
> Oui, c'est Olivier et moi qui l'avons corrigé. Je m'en excuse mais nous pouvons tous commettre des erreurs ou des oublis.
> Je ne connais aucun codeur qui n'ai jamais fait d'oubli dans la vie et c'est le but des pull request d'éviter cela.
> C'est pour cela que je vous invite à regarder attentivement chaque pull request et de commenter si quelque chose ne va pas.

Je ne vois pas où j'ai dit qu'il existe des codeurs qui n'ont jamais fais d'erreurs, je pense que tu as pris ça personnellement c'était juste une remarque de review de code, rien de personnel. Comme toutes les remarques que je fais (Je t'invite à jeter un oeil à d'autres projets sur github tu verras que j'utilise le même ton que eux, tout simplement car un repo github est censé être impersonnel).

> > Il faut se décider sur les conventions : soit fonctions dans le .cpp soit dans le .hpp pas les deux ( Sauf cas de class/struct/fonction template)
> 
> -> Les templates peuvent se faire dans le cpp... De même que les classes et les structures
> -> Si tu remarque bien, il y a déjà des convventions : 2 lignes maximums pour les fonctions (hors entête) dans le .h, sinon .cpp
> -> Le inlining est rapide donc quand on le peux -> dans .h
> -> Si tu remarque bien, j'ai mis dans le .cpp les méthodes compliqués même s'il n'y a moins de 2 lignes OU les méthodes qui appelle des classes
> prototypées non implémentée dans le .h. Je fais l'include dans le .cpp (pour faire économiser du temps de compilation et éviter de recompiler plein pot)

Premier point, bien sur que les templates peuvent se faire dans le .cpp étant donné qu'il n'y a aucune différence entre un .cpp et un .hpp, le compilo mange du texte c'est tout, maintenant je t'invite à essayer de faire une implémentation d'une fonction template de classe dans un .cpp et tu vas vite comprendre pourquoi j'ai parlé des templates (Le fait que la fonction soit directement dans le .hpp permet au compilo d'instancier la fonction pour des paramètres template données tandis que si la fonction est défini dans un .cpp le développeur devra forcer l'instanciation de la fonction pour tous les paramètres templates au préalables).

> > Appeler via this->foo() ou foo() pas les deux
> 
> Effectivement. Remarque justifiée. Mais j'utilise jamais this-> SAUF si je juge que sans celui-ci, c'est ambigu pour celui qui va relire mon code 
> (dont moi dans 6 mois). Ce jugement d'ambiguité est tout à fait subjectif et non transposable d'un individu à l'autre.

Content de voir que tu ne l'as pas pris personnellement, personnellement je trouve justement ambiguë d'utiliser les deux conventions. A l'équipe de choisir.

> > Il faut arrêter d'utiliser C++11 ou supérieur juste pour faire beau ( Je fais référence par exemple au std::for_each avec une lambda horrible sachant que un simple for aurait été plus lisible mais qui plus est depuis C++ 11 le language dispose d'un for each)
> 
> Je te rappelle le TP pour la séance S06 de Patrice... C'est ce que l'on nous impose. Et je ne fait pas le beau, j'utilise ce rush JUSTEMENT pour m'entrainer et essayer de nouvelles choses.
> M'élever un peu en codage et non toujours rester au niveau bébé... Mais ça c'est un choix personnel qui ne regarde que moi.

Je me rappelle surtout que Patrice nous enseigne des features et que c'est à nous de savoir à quels moments les utilisées. Je trouve ça très bien que tu t'essayes à de nouvelles choses je le fais moi même d'ailleurs mais j'essaie d'évité de le faire sur un projet de groupe. Par ailleurs j'ai dit "Ne pas utiliser C++11 ou supérieur juste pour faire beau" et pas "pour faire le beau".

> > Les exceptions doivent héritées des bonnes exceptions de la STL (c-a-d http://en.cppreference.com/w/cpp/error/exception). Sinon cela peut amener a des exception jamais catché.
> 
> Dis ça à Patrice... Je ne fais qu'appliquer ce que l'on m'apprend. (on peut les catcher. De plus, c'est exceptions dont tu parle n'offre qu'une chose de plus, des explications
> incompréhensibles (erreur de lecture de mémoire à l'emplacement 0xFFFFFEA32F...). Qu'est-ce que tu vas faire avec ça?...). Moi, je n'ai besoin que d'un crash d'appli. Les explications
> personnes ne les lit et même si on les lisait, cela ne nous servirait à rien, on lance le debugger et on ferait du pas-à-pas pour corriger...

Non tu n'es pas censé ne faire qu'appliquer ce que l'on t'apprend, tu es censé être capable de réfléchir par toi même si Patrice ne fais pas hérité ces exceptions de la STL, je suis certains qu'il a une bonne raison pour cela. A contrario nous n'en avons pas. Il te suffira de passer deux secondes sur stackoverflow pour le vérifier par toi même. Un développeur qui utilise ta library et qui essaye de rattraper les exceptions de son programme via `std::exception` se retrouvera face à un problème lorsqu'il verra qu'il y a des exception non catchées et il devra comprendre que cela vient de ta library.

> > Vect3f et Vertex sont sémantiquement une valeur(cf value semantic vs reference semantic), donc une struct avec des attributs publiques serait plus approprié.
> 
> Pour moi, jamais de variable publique. Une struct est pour moi une classe de stockage, pas de traitement mais cela n'est que subjectif et ne regarde que moi. Le code final est le même. On fait du C++, pas du C. Je prône l'encapsulation des variables. 
> Même s'il y a getter et setter, ce n'est pas une raison de tout passer en public. Mais encore une fois, cela ne regarde que ma façon de coder.

Non ça ne regarde pas du tout que ta façon de coder car premièrement nous sommes en groupe et deuxièmement je te laisse prendre le temps de te renseigné sur la value semantic et la référence semantic et revenir me donner un avis. ( De plus Gaspard nous avais conseiller de faire des structures)

> > Faire attention à ce que représente les fonctions, operator-= devrait être défini grâce a operator- et pas le contraire ! trop de copies inutiles !
> 
> Ok, propose moi une version où on fait l'inverse. Plus optimisé que celle-ci et surtout que si on veux faire un changement, on ne change qu'1 seule fois à 1 endroit.

Pas compris. (Pour info en BNF `a -= b` est l'équivalent de `a = a - b` et produit ce dernier arbre syntaxique ce qui veut dire que `-=` est défini par `-` et pas l'inverse)

Concernant la conception :

> Et j'aimerais bien que tu me proposes une solution simple et réutilisable pour créer un tableau de triangle sans avoir défini ce qu'était un triangle.
> En tout cas, c'est ma façon de coder et d'aborder les problèmes => quand on a un problème complexe, on le brise en ensemble de sous problèmes élémentaires et une classe résout 1 problème en particulier. C'est l'ensemble qui résout le problème de départ. Une classe qui résout 10 problèmes à la fois n'est pas une bonne idée, c'est d'expérience que je le dis...

Il me semble d'expérience avec OpenGL que l'ont fournis un tableau de vertexes contenant toutes les informations (Normales, Couleurs, Position) à la library et que l'ont décris à cette dernière le format des données dans ce tableau par exemple les 3 premiers floats correspondent à la position, les 3 suivant à une couleur, etc. Ceci dans le but de réduire les transferts de données CPU vers GPU. A voir avec le prof d'infographie

> > Une classe Terrain qui possède un constructeur prenant en paramètre une const &Heightmap qui construit les vertices/vertexes à partir des data de la Heightmap. Cette classe s'occupe aussi de calculer les normales. Elle possède aussi une fonction Draw() non implémenté encore qui enverra les données au GPU pour déssiner le terrain.
> 
> Idée qui pour moi est non recevable. Une classe fourre-tout en somme. Et pourquoi pas tout faire dans le main.cpp à ce moment là, c'est encore plus simple.

En quoi cette classe est-elle une classe fourre-tout le terrain a besoin de coordonnées pour exister nous lui fournissons la Heightmap qui contient les coordonnées nécessaire à son initialisation, la fonction Draw est aussi une fonction indissociable de cet objet, à la rigueur le calcul des normales pourrait être effectué par la Heightmap au préalable.

Je tiens encore à rappeler à tout le monde que ceci n'a rien de personnel j'essaie juste de faire de mon mieux pour que l'équipe sorte les meilleurs projets possibles.

**Comment by SunlayGGX** [comment]
Bon, je pense que on va aller un peu loin comme ça. Inutile de continuer, nous avons des avis et des expériences différents quand il s'agit de coder. 
Mais simplement, une petite chose avant de clore ce sujet : Nous ne faisons pas de librairie mais résolvons un problème qui nous est donné. Ici, le problème est de sérialiser un heightmap. Faire des .h ou des .hpp. Faire une classe ou une struct. Hériter une exception des librairies standard ou appeler using namespace Machin ou bien using Machin::Name ne change absolument rien. Peu importe comment je l'ai codé, au final, mes classes font le job. 

Je met à disposition des services que vous utiliserez ou n'utiliserez pas, c'est à vous de voir. Comment c'est fait à l'intérieur n'est pas très important, ce qui est important c'est qu'il n'y ait pas de bug à la sortie... Peu importe le nombre ou la façon dont vous appelez mes classes.

Je pense que tu seras d'accord sur ce fait : tu ne dois pas coder comme moi ni moi coder comme toi ni personne coder comme nous. On a laissé suffisamment de liberté dans les règles de codage pour que nous puissions coder des algorithmes comme on l'entend. Sachant que le résultat ne sera pas forcément meilleur ni avec ma façon de coder, ni ta façon de coder ni celle de personne.

Ah, et s'il y a un cours de C++ et que l'on nous met un prof, ce n'est pas pour rien. Très certainement que Patrice est largement meilleur que nous tous réunis. Il n'y a aucun mal à vouloir apprendre d'un codeur qui a plusieurs niveau au dessus (surtout qu'il a expliqué certaines raisons de ce qu'il fait comme le pourquoi de ces exceptions).

Bien cordialement ;)
